services:
  db:
    image: postgres:15
    container_name: vod-db
    restart: always
    environment:
      POSTGRES_USER: vodusr
      POSTGRES_PASSWORD: pass@1886
      POSTGRES_DB: vodb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - vod-net

  vodservice:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vod-app
    depends_on:
      - db
      - redis
    environment:
      PGHOST: localhost
      PGUSER: vodusr
      PGPASSWORD: pass@1886
      PGDATABASE: vodb
      REDIS_URL: redis://redis:6379
      JWT_SECRET: gc9,&jZ)=|;U_6|@8\U96B
    networks:
      - vod-net

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - vod-net

volumes:
  pgdata:

networks:
  vod-net:
    driver: bridge
