// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AuthResponse struct {
	Token string `json:"token"`
	User  *User  `json:"user"`
}

type Comment struct {
	ID        string `json:"id"`
	Video     *Video `json:"video"`
	User      *User  `json:"user"`
	Text      string `json:"text"`
	CreatedAt string `json:"created_at"`
}

type Mutation struct {
}

type Query struct {
}

type Subscription struct {
}

type User struct {
	ID        string `json:"id"`
	Username  string `json:"username"`
	Email     string `json:"email"`
	Role      string `json:"role"`
	CreatedAt string `json:"created_at"`
}

type Video struct {
	ID          string         `json:"id"`
	Title       string         `json:"title"`
	Description *string        `json:"description,omitempty"`
	URL         string         `json:"url"`
	Views       int            `json:"views"`
	Metadata    map[string]any `json:"metadata,omitempty"`
	Uploader    *User          `json:"uploader"`
	CreatedAt   string         `json:"created_at"`
}
